### PR TITLE
Create _top_nav_for_home.php

### PR DESCRIPTION
**Pull request by demyr17**
I wanted to change the background color of the header part which keeps logo and menu. As I only want to make it for the home page, I have created a separate/a copy of top_nav layout for the home page.  So that I could assign a different id for home page header.

### CODE REVIEW

**Comment by lonnieezell** [comment]
If the only thing changing is the background color, I think duplicating the entire thing is unnecessary. Couldn't we use a class or the header and wrap it in a div with a `home` class so that it can be targeted without duplicating code?

**Comment by MGatner** [comment]
I always include two additional sections in my main layouts to allow individual views to supply their own overriding script/style tags. E.g.:
https://github.com/duke-bluesmith/bluesmith/blob/2f76f3f4cf437182f7ed4f85efaf6c55160c95b9/app/Views/layouts/public.php#L38-L41
https://github.com/duke-bluesmith/bluesmith/blob/2f76f3f4cf437182f7ed4f85efaf6c55160c95b9/app/Views/layouts/public.php#L107-L110

I would be happy to implement that here, which would offer an easy version of what Lonnie is describing.

**Comment by demyr17** [comment]
Sorry for my late reply. Can you arrange 2 different layouts for 2 different pages without any condition? The covering home div will not be used on other pages.

**Comment by demyr17** [comment]
I have made a change following the suggestion of Lonnie.

**Comment by MGatner** [comment]
@demyr17 I created #82 with the new sections. If the home page needs its own CSS you can add it to the appropriate section. Like if you wanted the home page only to have a white background on the top nav you could put this at the bottom of **home.php**:
```
<?= $this->section('footerAssets') ?>
<style>

header {
    background-color: white;
}
<?= $this->endSection() ?>
```

**Comment by MGatner** [comment]
Handled by #84

**Pull request closed without merging**
