### PR TITLE
Update _top_nav.php

### PR DESCRIPTION
**Pull request by demyr17**
Instead of having two different headers for home page and other pages, I have added a <div> holding <header></header> part as Lonnie suggested. There will be a css equivalent for this change.

### CODE REVIEW

**Comment by MGatner** [comment]
I still don't think this is quite right - this will apply the ID to every page that uses the layout. Don't we just want the special header on the homepage, and not other pages? Or did I misunderstand that?

**Comment by demyr17** [comment]
You got it right. No misunderstanding. We need white background for the header part only for the home page. To do that, first I duplicated the code, then I changed it after Lonnie's suggestion... both way it worked.

**Comment by MGatner** [comment]
@demyr17 check out #84 and the conversation there please!

**Comment by MGatner** [comment]
Handled by #84

**Pull request closed without merging**
